### ISSUE TITLE
Now incomatible nokogiri with git scribe

### ISSUE THREAD

**Issue by abtris** [schacon/git-scribe#20]
git scribe check

/Library/Ruby/Gems/1.8/gems/nokogiri-1.4.4/lib/nokogiri/nokogiri.bundle: dlopen(/Library/Ruby/Gems/1.8/gems/nokogiri-1.4.4/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: /opt/local/lib/libiconv.2.dylib (LoadError)
  Referenced from: /Library/Ruby/Gems/1.8/gems/nokogiri-1.4.4/lib/nokogiri/nokogiri.bundle
  Reason: Incompatible library version: nokogiri.bundle requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0 - /Library/Ruby/Gems/1.8/gems/nokogiri-1.4.4/lib/nokogiri/nokogiri.bundle
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in `require'
    from /Library/Ruby/Gems/1.8/gems/nokogiri-1.4.4/lib/nokogiri.rb:13
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in `require'
    from /Library/Ruby/Gems/1.8/gems/git-scribe-0.0.9/bin/../lib/git-scribe.rb:2
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in `require'
    from /Library/Ruby/Gems/1.8/gems/git-scribe-0.0.9/bin/git-scribe:4
    from /usr/bin/git-scribe:19:in`load'
    from /usr/bin/git-scribe:19

**Comment by abtris** [comment]
Fixed by reinstall

# the rest of this snippet assumes installation of libxml 2.7.7. YMMV.

brew install libxml2
brew link libxml2

# install libxslt from source

wget ftp://xmlsoft.org/libxml2/libxslt-1.1.26.tar.gz
tar -zxvf libxslt-1.1.26.tar.gz
cd libxslt-1.1.26
./configure --prefix=/usr/local/Cellar/libxslt/1.1.26 \
            --with-libxml-prefix=/usr/local/Cellar/libxml2/2.7.7
make
sudo make install

gem install nokogiri -- --with-xslt-dir=/usr/local/Cellar/libxslt/1.1.26
