### ISSUE TITLE
PDF generation not working on mac OS Lion

### ISSUE THREAD

**Issue by gravis** [schacon/git-scribe#25]
Hello,

Right after doing 

```
git-scribe init
git-scribe gen pdf
```

I have this error :

``` none
GENERATING PDF
GENERATING DOCBOOK

I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/fo/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/fo/docbook.xsl"
compilation error: file /Users/gravis/.rvm/gems/ruby-1.8.7-p330/gems/git-scribe-0.0.9/docbook-xsl/fo.xsl line 16 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/fo/docbook.xsl

USAGE
fop [options] [-fo|-xml] infile [-xsl file] [-awt|-pdf|-mif|-rtf|-tiff|-png|-pcl|-ps|-txt|-at [mime]|-print] <outfile>
 [OPTIONS]  
  -version          print FOP version and exit
  -d                debug mode   
  -x                dump configuration settings  
  -q                quiet mode  
  -c cfg.xml        use additional configuration file cfg.xml
  -l lang           the language to use for user information 
  -r                relaxed/less strict validation (where available)
  -dpi xxx          target resolution in dots per inch (dpi) where xxx is a number
  -s                for area tree XML, down to block areas only
  -v                run in verbose mode (currently simply print FOP version and continue)

  -o [password]     PDF file will be encrypted with option owner password
  -u [password]     PDF file will be encrypted with option user password
  -noprint          PDF file will be encrypted without printing permission
  -nocopy           PDF file will be encrypted without copy content permission
  -noedit           PDF file will be encrypted without edit content permission
  -noannotations    PDF file will be encrypted without edit annotation permission
  -a                enables accessibility features (Tagged PDF etc., default off)
  -pdfprofile prof  PDF file will be generated with the specified profile
                    (Examples for prof: PDF/A-1b or PDF/X-3:2003)

  -conserve         Enable memory-conservation policy (trades memory-consumption for disk I/O)
                    (Note: currently only influences whether the area tree is serialized.)

 [INPUT]  
  infile            xsl:fo input file (the same as the next) 
                    (use '-' for infile to pipe input from stdin)
  -fo  infile       xsl:fo input file  
  -xml infile       xml input file, must be used together with -xsl 
  -atin infile      area tree input file 
  -ifin infile      intermediate format input file 
  -imagein infile   image input file (piping through stdin not supported)
  -xsl stylesheet   xslt stylesheet 

  -param name value <value> to use for parameter <name> in xslt stylesheet
                    (repeat '-param name value' for each parameter)

  -catalog          use catalog resolver for input XML and XSLT files
 [OUTPUT] 
  outfile           input will be rendered as PDF into outfile
                    (use '-' for outfile to pipe output to stdout)
  -pdf outfile      input will be rendered as PDF (outfile req'd)
  -pdfa1b outfile   input will be rendered as PDF/A-1b compliant PDF
                    (outfile req'd, same as "-pdf outfile -pdfprofile PDF/A-1b")
  -awt              input will be displayed on screen 
  -rtf outfile      input will be rendered as RTF (outfile req'd)
  -pcl outfile      input will be rendered as PCL (outfile req'd) 
  -ps outfile       input will be rendered as PostScript (outfile req'd) 
  -afp outfile      input will be rendered as AFP (outfile req'd)
  -tiff outfile     input will be rendered as TIFF (outfile req'd)
  -png outfile      input will be rendered as PNG (outfile req'd)
  -txt outfile      input will be rendered as plain text (outfile req'd) 
  -at [mime] out    representation of area tree as XML (outfile req'd) 
                    specify optional mime output to allow the AT to be converted
                    to final format later
  -if [mime] out    representation of document in intermediate format XML (outfile req'd)
                    specify optional mime output to allow the IF to be converted
                    to final format later
  -print            input file will be rendered and sent to the printer 
                    see options with "-print help" 
  -out mime outfile input will be rendered using the given MIME type
                    (outfile req'd) Example: "-out application/pdf D:\out.pdf"
                    (Tip: "-out list" prints the list of supported MIME types)
  -svg outfile      input will be rendered as an SVG slides file (outfile req'd) 
                    Experimental feature - requires additional fop-sandbox.jar.

  -foout outfile    input will only be XSL transformed. The intermediate 
                    XSL-FO file is saved and no rendering is performed. 
                    (Only available if you use -xml and -xsl parameters)


 [Examples]
  fop foo.fo foo.pdf 
  fop -fo foo.fo -pdf foo.pdf (does the same as the previous line)
  fop -xml foo.xml -xsl foo.xsl -pdf foo.pdf
  fop -xml foo.xml -xsl foo.xsl -foout foo.fo
  fop -xml - -xsl foo.xsl -pdf -
  fop foo.fo -mif foo.mif
  fop foo.fo -rtf foo.rtf
  fop foo.fo -print
  fop foo.fo -awt

Aug 1, 2011 12:34:47 PM org.apache.fop.cli.Main startFOP
SEVERE: Exception
java.io.FileNotFoundException: Error: fo file /Users/gravis/temp/procedures/output/book.fo not found 
    at org.apache.fop.cli.CommandLineOptions.checkSettings(CommandLineOptions.java:941)
    at org.apache.fop.cli.CommandLineOptions.parse(CommandLineOptions.java:167)
    at org.apache.fop.cli.Main.startFOP(Main.java:158)
    at org.apache.fop.cli.Main.main(Main.java:205)
```

I have ﻿﻿version 0.0.9 installed, along with fop 1.0.
Thanks :)

**Comment by ACodeFarmer** [comment]
Same problem here. :)

**Comment by markbates** [comment]
same here.

**Comment by xdite** [comment]
Hi, try 

brew install docbook 
sudo docbook-register

**Comment by gravis** [comment]
Works like a charm for me. 
Thanks !
